### ISSUE TITLE
Test accuracy issues

### ISSUE THREAD

**Issue by qiynxx** [yuhongtian17/Spatial-Transform-Decoupling#3]
Hello, I used the "STD with Oriented RCNN and HiViT-B" model to evaluate on the test on DOTA1.0. I used the server of the DOTA official website for evaluation. The evaluation mAP result was 81.06, which is consistent with the 82.24 mentioned in the paper. A little difference, why?

This is your evaluation result for task 1 (VOC metrics):

mAP: 0.810575436363946
ap of each class: plane:0.8933205505601759, baseball-diamond:0.8546187703978203, bridge:0.6084318178731625, ground-track-field:0.771691793850593, small-vehicle:0.8200260438071499, large-vehicle:0.8632254332213434, ship:0.885131435672446, tennis-court:0.9082192805520113, basketball-court:0.8694354930430841, storage-tank:0.8752284047755186, soccer-ball-field:0.6751423105913145, roundabout:0.7031438867654732, harbor:0.7904160127746516, swimming-pool:0.8438027909132928, helicopter:0.796797520661157
COCO style result:

AP50: 0.810575436363946
AP75: 0.5922003698598682
mAP: 0.5332139760859933

**Comment by yuhongtian17** [comment]
We checked our experimental records and found that 81.06% mAP was the result of this pth file on the single-scale test ("./data/split_ss_dota/") while 82.24% mAP was the result on the multi-scale test ("./data/split_ms_dota/").

In an ms-test config file, you should write:

```python
data_root_ms = 'data/split_ms_dota/'
angle_version = 'le90'
data = dict(
    test=dict(
        ann_file=data_root_ms + 'test/images/',
        img_prefix=data_root_ms + 'test/images/',
        version=angle_version))
```

Then you will get the correct result!

**Comment by yaosx425** [comment]
> We checked our experimental records and found that 81.06% mAP was the result of this pth file on the single-scale test ("./data/split_ss_dota/") while 82.24% mAP was the result on the multi-scale test ("./data/split_ms_dota/").
> 
> In an ms-test config file, you should write:
> 
> ```python
> data_root_ms = 'data/split_ms_dota/'
> angle_version = 'le90'
> data = dict(
>     test=dict(
>         ann_file=data_root_ms + 'test/images/',
>         img_prefix=data_root_ms + 'test/images/',
>         version=angle_version))
> ```
> 
> Then you will get the correct result!

I tried to use the img_split.py in the tools/dota/split folder to process the DOTA dataset, but I got the error shown in the figure.
![image](https://github.com/yuhongtian17/Spatial-Transform-Decoupling/assets/142800903/fa03a04b-fe64-4ade-86a5-cd56dc606ada)
