### ISSUE TITLE
Download pretrained model

### ISSUE THREAD

**Issue by xlomin8** [yuhongtian17/Spatial-Transform-Decoupling#5]
Currently, I have to download the installer of BaiduNetwork and login to get the pretrained model.(https://pan.baidu.com/s/19nw-Ry2pGoeHZ0lQ-XehQg#list/path=%2FSpatial-Transform-Decoupling-Models%2Frotated_imted_vb1m_oriented_rcnn_vit_base_1x_dota_ms_rr_le90_stdc_xyawh321v%20(240330%20updated)) 
But I'm worried about the possibility of misusal of my personal information.

Is there another way to download your pretrained model (not Imagenet MAE pre-trained ViT-B backbone, but [rotated_imted_vb1m_oriented_rcnn_vit_base_1x_dota_ms_rr_le90_stdc_xyawh321v (240330 updated)]) without login Baidu website? Could you just upload at your github page plz?

**Comment by yuhongtian17** [comment]
Unfortunately, we only have this way to store and release our weight files currently. You can provide tutorials to help us learn how to store and release large files (larger than 100MB and less than 2GB for a single file) on GitHub. If you need this weight file urgently, you can send a private email to yuhongtian17@mails.ucas.ac.cn and we will send it to you as an attachment in the reply email.

**Comment by yuhongtian17** [comment]
All models can be downloaded in [release](https://github.com/yuhongtian17/Spatial-Transform-Decoupling/releases/tag/STD-240413) mode now!
