### ISSUE TITLE
Dependencies compatibility

### ISSUE THREAD

**Issue by theoh-io** [yuhongtian17/Spatial-Transform-Decoupling#7]
Hello,

Thanks for sharing the code and weights for this model.

I am currently trying to setup the project on my personal laptop
I previously tried with my regular setup: WSL Ubuntu20.04, python3.10, cuda12.1 and latest pytorch version gut got an error.

Following your recommendation I started a new WSL instance on Ubuntu 18 with python3 and made sure to install cuda toolkit 10.2 and pytorch 1.7, I get torch.cuda is available however I still get RuntimeError: CUDA error: no kernel image is available for execution on the device.

From what I understood my GPU(RTX4060) needs latest (12.x) CUDA version.

Do you have any idea on how I could solve this ?
Do you plan on releasing compatible updates with cuda 12.x ?

**Comment by yuhongtian17** [comment]
[NVIDIA](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) do not recommend using CUDA 10.2 with RTX 40 series GPU. Our RTX 4090 GPU with {cuda toolkit 11.6, python 3.8, pytorch 1.12.1, mmcv==1.6.1, mmdet==2.25.1, mmrotate==0.3.4, numpy==1.21.5, yapf==0.40.1} can run the code.
